---
services:
  adguard:
    image: adguard/adguardhome:v0.107.74
    container_name: adguard
    volumes:
      - /srv/prod/adguard/work:/opt/adguardhome/work
      - /srv/prod/adguard/conf:/opt/adguardhome/conf
    network_mode: host
    cap_add:
      - NET_ADMIN
    restart: unless-stopped
