---
- name: Check if adguard data directories already exist
  become: true
  ansible.builtin.file:
    path: '/srv/prod/adguard/{{ item }}'
    state: directory
    mode: '0700'
    access_time: preserve
  loop:
    - work
    - conf
