---
- name: Create data directory.
  become: true
  ansible.builtin.file:
    dest: /srv/prod/forgejo_runner/data
    state: directory
    mode: "0755"
    access_time: preserve

- name: Create .cache directory.
  become: true
  ansible.builtin.file:
    dest: /srv/prod/forgejo_runner/data/.cache
    state: directory
    owner: "1001"
    group: "1001"
    mode: "0775"
    access_time: preserve
