---
- name: Ensure home assistant config directory exists
  become: true
  ansible.builtin.file:
    path: /srv/prod/home_assistant/config
    state: directory
    mode: '0700'
    access_time: preserve
