all:
  children:
    linux:
      children:
        servers:
          hosts:
            hp_server:
              ansible_host: 10.5.15.8
              services_to_run:
                - ollama
                - openwebui
                - adguard
                - home_assistant
                - ntfy
                - simon
                - traefik
                - vaultwarden
                - wireguard
                - forgejo
                - forgejo_runner
                - rclone_webdav
                - postgres
                - immich
        workstations:
          hosts:
            laptop_dell:
              ansible_connection: local
