all:
  children:
    linux:
      children:
        servers:
          hosts:
            hp_server:
              ansible_host: 10.5.15.8
              services_to_run:
                - ollama
                - adguard
                - home_assistant
                - paperlessngx
                - ntfy
                - simon
                - pocket_id
                - traefik
                - vaultwarden
                - forgejo
                - forgejo_runner
                - rclone_webdav
                - postgres
                - immich
                - gluetun
                - searxng
                - headscale
                - crowdsec
        workstations:
          hosts:
            laptop_dell:
              ansible_connection: local
