networks:
  forgejo:
    external: false
  proxy:
    external: true

services:
  server:
    image: codeberg.org/forgejo/forgejo:14
    container_name: forgejo
    environment:
      - USER_UID=1000
      - USER_GID=1000
    restart: always
    networks:
      - forgejo
      - proxy
    volumes:
      - /srv/prod/forgejo:/data
      - /etc/localtime:/etc/localtime:ro
    ports:
      - '222:22'
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.forgejo.tls=true"
      - "traefik.http.routers.forgejo.rule=Host(`git.jhomelab.net`)"
      - "traefik.http.routers.forgejo.entrypoints=https"
      - "traefik.http.routers.forgejo.service=forgejo"
      - "traefik.http.routers.forgejo.middlewares=default-headers@file"
      - "traefik.http.services.forgejo.loadbalancer.server.port=3000"
