services:
  openwebui:
    image: ghcr.io/open-webui/open-webui:main
    networks:
      - proxy
    volumes:
      - /srv/prod/openWebUi:/app/backend/data
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.open-web-ui.tls=true"
      - "traefik.http.routers.open-web-ui.rule=Host(`ai.jhomelab.net`)"
      - "traefik.http.routers.open-web-ui.entrypoints=https"
      - "traefik.http.routers.open-web-ui.service=open-web-ui"
      - "traefik.http.routers.open-web-ui.middlewares=default-headers@file,compress@file"
      - "traefik.http.services.open-web-ui.loadbalancer.server.port=8080"

networks:
  proxy:
    external: true
