---
- name: Add Docker repository
  ansible.builtin.get_url:
    url: https://download.docker.com/linux/centos/docker-ce.repo
    dest: /etc/yum.repos.d/docker-ce.repo
    mode: "0644"

- name: Install docker engine
  ansible.builtin.dnf:
    name:
      - docker-ce
      - docker-ce-cli
      - containerd.io
      - docker-buildx-plugin
      - docker-compose-plugin
    state: present
    update_cache: true

- name: Ensure custom docker directory is created
  ansible.builtin.file:
    path: /srv/prod/docker
    state: directory
    owner: root
    group: root
    mode: "0711"

- name: Update docker data root.
  ansible.builtin.copy:
    dest: /etc/docker/daemon.json
    content: |
      { "data-root": "/srv/prod/docker" }
    mode: "0644"
  notify: restart-docker

- name: Start docker
  ansible.builtin.service:
    name: docker
    state: started
    enabled: true
