---
- name: Ensure firewalld is installed and running
  ansible.builtin.service:
    name: firewalld
    state: started
    enabled: true

- name: Apply firewalld rules
  ansible.posix.firewalld:
    zone: "{{ item.zone }}"
    target: "{{ item.target | default(omit) }}"
    source: "{{ item.source | default(omit) }}"
    service: "{{ item.service | default(omit) }}"
    port: "{{ item.port | default(omit) }}"
    state: "{{ item.state }}"
    permanent: "{{ item.permanent }}"
  loop: "{{ firewalld_rules }}"
  notify: Reload firewalld
