---
- name: Configure SSH
  ansible.builtin.include_tasks: ssh.yml

- name: Check if Docker is installed
  ansible.builtin.command: docker --version
  register: server_docker_version
  failed_when: false
  changed_when: false

- name: Show Docker installation status
  ansible.builtin.debug:
    msg: "Docker is installed. Version: {{ server_docker_version.stdout }}"
  when: server_docker_version.rc == 0

- name: Install Docker Engine
  ansible.builtin.include_tasks: docker_engine.yml
  when: server_docker_version.rc !=0

- name: Set up firewalld
  ansible.builtin.include_tasks: firewalld.yml
  when: ansible_facts['os_family'] == "RedHat"
