---

- name: Create data directory.
  become: true
  ansible.builtin.file:
    dest: /srv/prod/forgejo-runner/data
    state: directory
    mode: '0755'
    access_time: preserve

- name: Create .cache file.
  become: true
  ansible.builtin.file:
    dest: /srv/prod/forgejo-runner/data/.cache
    state: directory
    mode: '0755'
    access_time: preserve

- name: Copy docker compose file.
  become: true
  ansible.builtin.copy:
    src: docker-compose.yaml
    dest: /srv/prod/docker-compose-runner.yaml
    mode: '0600'
