---
- name: Ensure all groups are created before creating users
  ansible.builtin.group:
    name: "{{ user_group_item.name }}"
    gid: "{{ user_group_item.gid }}"
    state: present
  loop: "{{ user_groups }}"
  loop_control:
    loop_var: user_group_item
  when: user_groups | length > 0

- name: Create users
  ansible.builtin.user:
    name: "{{ user_item.name }}"
    groups: "{{ user_item.groups }}"
    uid: "{{ user_item.uid }}"
    shell: "{{ user_item.shell | default(None) }}"
    home: "{{ user_item.home | default(None) }}"
    create_home: "{{ user_item.create_home | default(true) }}"
    state: present
  loop: "{{ users }}"
  loop_control:
    loop_var: user_item
  when: users | length > 0

- name: Add SSH keys for users
  ansible.posix.authorized_key:
    user: "{{ user_ssh_item.name }}"
    key: "{{ user_ssh_item.ssh_key }}"
    state: present
  loop: "{{ users }}"
  loop_control:
    loop_var: user_ssh_item
  when:
    - users | length > 0
    - item.ssh_key is defined
