---
- name: Deploy containers
  hosts: all
  gather_facts: false
  become: true

  tasks:
    - name: Deploy Docker Services
      ansible.builtin.include_role:
        name: docker_services
      when: services_to_run is defined
