name: CI

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  lint:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: "3.14"

      - name: Install dependencies
        run: pip install ansible-lint

      - name: Run Ansible Lint
        env:
          ANSIBLE_VAULT_PASSWORD: "${{ secrets.VAULT_PASSWORD }}"
          ANSIBLE_VAULT_PASSWORD_FILE: ./scripts/vault_pass.sh
        run: |
          chmod +x scripts/vault_pass.sh
          ansible-lint -c .ansible-lint.yaml
